### PR TITLE
190 import scritps

### PR DESCRIPTION
**Pull request by cahytinne**
#190

### CODE REVIEW

**Comment by BartSaelen** [comment]
tests falen, eerst nakijken wat hier het probleem is

    platform linux -- Python 3.4.0 -- py-1.4.26 -- pytest-2.6.3
    plugins: cov
    collected 204 items 
    
    tests/test_config.py .
    tests/test_datamanagers.py ....................
    tests/test_errors.py .......
    tests/test_functional.py .............F.............F...............F...............
    tests/test_import_scripts.py ...
    tests/test_mappers.py ..........
    tests/test_protected_resources.py ...
    tests/test_renderes.py .......
    tests/test_scaffold.py ..
    tests/test_skos.py .
    tests/test_utils.py ......
    tests/test_validation.py ......................................................
    tests/test_views.py ...............................

**Comment by cahytinne** [comment]
It is caused by the latest version of pyramid-skosprovider, more specifically to the [note_adapter](
https://github.com/koenedaele/pyramid_skosprovider/blob/master/pyramid_skosprovider/utils.py#L121). Is the markup attribute obligated? Otherwise I would change it to
```python
def note_adapter(obj, request):
    '''
    Adapter for rendering a :class:`skosprovider.skos.Note` to json.

    :param skosprovider.skos.Note obj: The note to be rendered.
    :rtype: :class:`dict`
    '''
    return {
        'note': obj.note,
        'type': obj.type,
        'language': obj.language,
        'markup': obj.markup if obj.markup else None 
    }
```

cc @koenedaele

**Comment by koenedaele** [comment]
That's a new attribute to enable support for markup in notes. You need to upgrade to the latest version of skosprovider.

**Comment by cahytinne** [comment]
The tests still fail with the latest version of skosprovider. Could it that the markup attribute for notes has to be included aswell in skosprovider_sqlalchemy?

**Comment by koenedaele** [comment]
Probably. I didn't get round to updating skosprovider_sqlalchemy yet. Can you send a PR? I'll review and merge.

**Comment by koenedaele** [comment]
PR was accepted. Requirements file can point back to master again.

**Pull request merged**
