### PR TITLE
Fix alembic for altering concept_id to string.

### PR DESCRIPTION
**Pull request by Wim-De-Clercq**
I've already tested this PR with https://github.com/OnroerendErfgoed/atramhasis/pull/818

All tests become green except one: `test_import_scripts#test_import_json`

I can fix it by adding the 2 session lines to it:
```py
self.session.commit()
self.session.expire_all()
self._check_trees('Trees Conceptscheme')
```

Because when we import a provider, we don't specifically cast the concept ID from the original provider to a string when creating the `Concept` DB objects. 
We just do
```
concept_id=c.id,
^             ^
|             -- original provider ID, can be anything, in this case an integer
|
|
-- database object concept_id -- expected to be string
```
The change / cast into a string happens automagically in the database.

But SQLAlchemy tries to be smart and caches these `Concept` objects which hold an integer concept_id -- while it's stored as a string in the database. So by committing and expiring the objects, I force SQLAlchemy to fetch them from the database again, and they will be a String as expected.

I have no idea why this is an issue only with https://github.com/OnroerendErfgoed/atramhasis/pull/818 and not already on this one too.

### CODE REVIEW

**Review by vancamti — APPROVED** [review]

**Review by koenedaele — APPROVED** [review]
I'm fine with this fix. But should we also make sure the import_provider function does the cast? Then there's no ambivalence?

**Comment by Wim-De-Clercq** [comment]
Waarschijnlijk wel, dit zit wel in skosprovider_sqlalchemy.

**Comment by koenedaele** [comment]
Created a ticket in OnroerendErfgoed/skosprovider_sqlalchemy#104

**Comment by koenedaele** [comment]
skosprovider_sqlalchemy 2.2.1 has been released. This version forces the cast to str before passing to SQLAlchemy.

**Comment by Wim-De-Clercq** [comment]
Can confirm, after merging #818 with this PR all tests now become green without needing extra changes.

**Pull request merged**
