### PR TITLE
Add GET provider endpoints.

### PR DESCRIPTION
**Pull request by Wim-De-Clercq**

### CODE REVIEW

**Review by koenedaele — COMMENTED** [review]
- Should we update the Swagger API docs as well?
- Should we validate the subject search parameter as being as string?

**Comment by Wim-De-Clercq** [comment]
query parameters are always strings.
swagger definitely yes.

**Comment by Wim-De-Clercq** [comment]
I used swagger to validate anyway.
If I took the effort to write swagger, we might as well use it.

**Comment by koenedaele** [comment]
@vancamti Could you review this one as well, then frontend can get on with it :-)

**Review by vancamti — APPROVED** [review]

**Pull request merged**
